Update ci-cd.yml by adding norm check

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -34,8 +34,21 @@ jobs:
       - name: make for makefile
         run: timeout 2m make
 
-  push_to_mirror:
+  check_norm:
     needs: check_program_compilation
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      
+      - name: test norm
+        run: |
+          if [[ -z "$(wget https://raw.githubusercontent.com/Epitech/coding-style-checker/main/coding-style.sh && echo "no" | bash coding-style.sh . . | grep "0 major, 0 minor")" ]]; then
+              echo "::error title=Norm not respected GUY"
+              exit 1
+          fi
+
+  push_to_mirror:
+    needs: check_norm
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
